export const TABLE_IMAGE_OVERRIDES: Record<string, string> = {
    '4': '/sushidemaksim_black_style_photos/Clasico_con_anguila_black.webp',
    '5': '/sushidemaksim_black_style_photos/Clasico_con_atun_black.webp',
    '6': '/sushidemaksim_black_style_photos/Clasico_con_Salmon_black.webp',
    '7': '/sushidemaksim_black_style_photos/Gyozas con carne_sushidemaksim_black.webp',
    '9': '/sushidemaksim_black_style_photos/Gunkan de Atun_black.webp',
    '10': '/sushidemaksim_black_style_photos/Langostinos fritos con salsa_black.webp',
    '11': '/sushidemaksim_black_style_photos/Nigiri de Anguila_sushidemaksim_black.webp',
    '12': '/sushidemaksim_black_style_photos/Tequenos con salsa_black.webp',
    '13': '/sushidemaksim_black_style_photos/Gunkan Pez Volador_black.webp',
    '15': '/sushidemaksim_black_style_photos/Gunkan Salmon Picante_black.webp',
    '16': '/sushidemaksim_black_style_photos/Gunkan Gamba Picante_black.webp',
    '17': '/sushidemaksim_black_style_photos/Nigiri Salmon_sushidemaksim_black.webp',
    '19': '/sushidemaksim_black_style_photos/Moncloa_sushidemaksim_black.webp',
    '21': '/sushidemaksim_black_style_photos/Rivas_sushidemaksim_black.webp',
    '22': '/sushidemaksim_black_style_photos/Dragon_sushidemaksim_black.webp',
    '23': '/sushidemaksim_black_style_photos/Canada_sushidemaksim_black.webp',
    '24': '/sushidemaksim_black_style_photos/California_sushidemaksim_black.webp',
    '25': '/sushidemaksim_black_style_photos/Chamartin_sushi_de_maksim_sushidemaksim_black.webp',
    '26': '/sushidemaksim_black_style_photos/philadelphia_sushidemaksim_black.webp',
    '27': '/sushidemaksim_black_style_photos/Chamberi_sushidemaksim_black.webp',
    '28': '/sushidemaksim_black_style_photos/Manzanares_sushidemaksim_black.webp',
    '29': '/sushidemaksim_black_style_photos/Getafe_sushi_de_maksim_black.webp',
    '30': '/sushidemaksim_black_style_photos/Estrella_sushi_de_maksim_black.webp',
    '32': '/sushidemaksim_black_style_photos/Sakura_sushidemaksim_black.webp',
    '35': '/sushidemaksim_black_style_photos/Clasico_con_aguacate_black.webp',
    '36': '/sushidemaksim_black_style_photos/Clasico_con_gambas_black.webp',
    '38': '/sushidemaksim_black_style_photos/Clasico_con_pepino_black.webp',
    '39': '/sushidemaksim_black_style_photos/Volcano_Roll_horneado_sushidemaksim_black.webp',
    '41': '/sushidemaksim_black_style_photos/Pacifico_roll_sushidemaksim_black.webp',
    '42': '/sushidemaksim_black_style_photos/Adelfas_roll_horneado_black.webp',
    '43': '/sushidemaksim_black_style_photos/Ventas_sushidemaksim_black.webp',
    '45': '/sushidemaksim_black_style_photos/Villaverde_sushidemaksim_black.webp',
    '46': '/sushidemaksim_black_style_photos/Vicalvoro_sushidemaksim_black.webp',
    '47': '/sushidemaksim_black_style_photos/Verano_roll_horneado_black.webp',
    '48': '/sushidemaksim_black_style_photos/Cubierto_de_amor_black.webp',
    '49': '/sushidemaksim_black_style_photos/Chef Gourmet_black.webp',
    '50': '/sushidemaksim_black_style_photos/Chef Gourmet XL_sushidemaksim_black.webp',
    '51': '/sushidemaksim_black_style_photos/4xl_sushidemaksim_black.webp',
    '52': '/sushidemaksim_black_style_photos/6xl_sushidemaksim_black.webp',
    '53': '/sushidemaksim_black_style_photos/5xl_sushidemaksim_black.webp',
    '54': '/sushidemaksim_black_style_photos/Jengibre_sushidemaksim_black.webp',
    '55': '/sushidemaksim_black_style_photos/Salsa_de_soja_black.webp',
    '56': '/sushidemaksim_black_style_photos/Wasabi_sushidemaksim_black.webp',
    '57': '/sushidemaksim_black_style_photos/palitos_black.webp',
    '63': '/sushidemaksim_black_style_photos/Rollitos de Primavera_sushidemaksim_black.webp',
    '95': '/sushidemaksim_black_style_photos/Alaska_sushidemaksim_black.webp',
    '100': '/sushidemaksim_black_style_photos/Furia_Roja_sushidemaksim_black.webp',
    '104': '/sushidemaksim_black_style_photos/Tom_Yum_sushidemaksim_black.webp',
    '105': '/sushidemaksim_black_style_photos/Fingers de mozzarella_sushidemaksim_black.webp',
    '106': '/sushidemaksim_black_style_photos/Mochi_artesano_sushidemaksim_black.webp',
    '107': '/sushidemaksim_black_style_photos/Sopa_cremosa_de_salmon_sushidemaksim_black.webp',
};
